// The NSIS script for the Append HMI Desktop installer (scripts/dist-win.mjs).
//
// It installs the unpacked app, a Start menu and desktop shortcut to the
// launcher, and the .ahmi file type:
//   - a "Run with Append HMI Desktop" verb on every .ahmi file
//     (SystemFileAssociations, so it works whatever program opens them);
//   - its own ProgID, which becomes the default for .ahmi only when nothing
//     else (Append HMI Studio) already is.
// A running copy is stopped first: a kiosk project cannot be closed normally.

import {nsisString, windowsFileName, fourPartVersion, COMPRESSION} from '../studio/src/main/publish/NsisScript.js';

// opts: productName, version, publisher, exeName, scope ('machine'|'user'),
// compression ('small'|'fast'), outFile, appDir, rootEntries and resources
// ([{name, dir}]), ext, progId, runVerb, runVerbLabel, installerIcon, join,
// estimatedSizeKb
export function buildDesktopNsis(opts)
{
	const q = nsisString;
	const join = opts.join;
	const machine = opts.scope === 'machine';
	const root = machine ? 'HKLM' : 'HKCU';
	const id = windowsFileName(opts.productName);
	const classes = 'Software\\Classes\\';
	const ext = '.' + opts.ext;
	const verbKey = classes + 'SystemFileAssociations\\' + ext + '\\shell\\' + opts.runVerb;
	const lines = [];
	const add = (...l) => lines.push(...l);

	add('; Generated by npm run dist-win',
		'Unicode true',
		'ManifestDPIAware true',
		`!define PRODUCT "${q(opts.productName)}"`,
		`!define EXE "${q(opts.exeName)}"`,
		`!define UNINST_KEY "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${q(id)}"`,
		'Name "${PRODUCT}"',
		`OutFile "${q(opts.outFile)}"`,
		`RequestExecutionLevel ${machine ? 'admin' : 'user'}`,
		`InstallDir "${machine ? '$PROGRAMFILES64' : '$LOCALAPPDATA\\Programs'}\\${q(id)}"`,
		`InstallDirRegKey ${root} "\${UNINST_KEY}" "InstallLocation"`,
		COMPRESSION[opts.compression] || COMPRESSION.small,
		...(opts.installerIcon ? [`Icon "${q(opts.installerIcon)}"`, `UninstallIcon "${q(opts.installerIcon)}"`] : []),
		'ShowInstDetails nevershow',
		'ShowUninstDetails nevershow',
		'',
		`VIProductVersion "${fourPartVersion(opts.version)}"`,
		'VIAddVersionKey "ProductName" "${PRODUCT}"',
		`VIAddVersionKey "ProductVersion" "${q(opts.version)}"`,
		`VIAddVersionKey "FileVersion" "${q(opts.version)}"`,
		'VIAddVersionKey "FileDescription" "${PRODUCT} Setup"',
		`VIAddVersionKey "CompanyName" "${q(opts.publisher)}"`,
		`VIAddVersionKey "LegalCopyright" "${q(opts.publisher)}"`,
		'',
		'Page instfiles',
		'UninstPage uninstConfirm',
		'UninstPage instfiles',
		'',
		// Stops the app, its helpers and hmi-comms, and waits up to 10 s
		'!macro StopApp',
		'  nsExec::Exec \'"$SYSDIR\\taskkill.exe" /F /T /IM "${EXE}"\'',
		'  Pop $0',
		'  StrCpy $1 0',
		'  stop_wait:',
		'  nsExec::Exec \'cmd /c tasklist /FI "IMAGENAME eq ${EXE}" /NH | find /I "${EXE}"\'',
		'  Pop $0',
		'  StrCmp $0 "0" 0 stop_gone',
		'  IntOp $1 $1 + 1',
		'  IntCmp $1 20 stop_gone',
		'  Sleep 500',
		'  Goto stop_wait',
		'  stop_gone:',
		'  Sleep 1000',
		'!macroend',
		'',
		'Function .onInit',
		'  SetRegView 64',
		machine ? '  SetShellVarContext all' : '  SetShellVarContext current',
		'FunctionEnd',
		'',
		'Function un.onInit',
		'  SetRegView 64',
		machine ? '  SetShellVarContext all' : '  SetShellVarContext current',
		'FunctionEnd',
		'',
		'Section "Install"',
		'  !insertmacro StopApp',
		'  RMDir /r "$INSTDIR\\resources"',
		'  RMDir /r "$INSTDIR\\locales"',
		'  SetOutPath "$INSTDIR"');

	for (const e of opts.rootEntries)
	{
		if (e.name === 'resources')
		{
			continue;
		}

		add(e.dir ? `  File /r "${q(join(opts.appDir, e.name))}"` : `  File "${q(join(opts.appDir, e.name))}"`);
	}

	add('  SetOutPath "$INSTDIR\\resources"');

	for (const e of opts.resources)
	{
		add(e.dir ? `  File /r "${q(join(opts.appDir, 'resources', e.name))}"` :
			`  File "${q(join(opts.appDir, 'resources', e.name))}"`);
	}

	add('  SetOutPath "$INSTDIR"',
		'  WriteUninstaller "$INSTDIR\\Uninstall.exe"',
		'  CreateShortcut "$SMPROGRAMS\\${PRODUCT}.lnk" "$INSTDIR\\${EXE}"',
		'  CreateShortcut "$DESKTOP\\${PRODUCT}.lnk" "$INSTDIR\\${EXE}"',
		'',
		// The file type: our ProgID, the Run verb, and the default only if free
		`  WriteRegStr ${root} "${classes}${q(opts.progId)}" "" "HMI Application"`,
		`  WriteRegStr ${root} "${classes}${q(opts.progId)}\\DefaultIcon" "" "$INSTDIR\\\${EXE},0"`,
		`  WriteRegStr ${root} "${classes}${q(opts.progId)}\\shell\\open" "" "Run"`,
		`  WriteRegStr ${root} "${classes}${q(opts.progId)}\\shell\\open\\command" "" '"$INSTDIR\\\${EXE}" "%1"'`,
		`  WriteRegStr ${root} "${classes}${ext}\\OpenWithProgids" "${q(opts.progId)}" ""`,
		`  WriteRegStr ${root} "${q(verbKey)}" "" "${q(opts.runVerbLabel)}"`,
		`  WriteRegStr ${root} "${q(verbKey)}" "Icon" "$INSTDIR\\\${EXE},0"`,
		`  WriteRegStr ${root} "${q(verbKey)}\\command" "" '"$INSTDIR\\\${EXE}" "%1"'`,
		`  ReadRegStr $0 HKCR "${ext}" ""`,
		'  StrCmp $0 "" 0 assoc_done',
		`  WriteRegStr ${root} "${classes}${ext}" "" "${q(opts.progId)}"`,
		'  assoc_done:',
		'  System::Call \'shell32::SHChangeNotify(i 0x08000000, i 0, p 0, p 0)\'',
		'',
		`  WriteRegStr ${root} "\${UNINST_KEY}" "DisplayName" "\${PRODUCT}"`,
		`  WriteRegStr ${root} "\${UNINST_KEY}" "DisplayVersion" "${q(opts.version)}"`,
		`  WriteRegStr ${root} "\${UNINST_KEY}" "Publisher" "${q(opts.publisher)}"`,
		`  WriteRegStr ${root} "\${UNINST_KEY}" "DisplayIcon" "$INSTDIR\\\${EXE}"`,
		`  WriteRegStr ${root} "\${UNINST_KEY}" "InstallLocation" "$INSTDIR"`,
		`  WriteRegStr ${root} "\${UNINST_KEY}" "UninstallString" '"$INSTDIR\\Uninstall.exe"'`,
		`  WriteRegStr ${root} "\${UNINST_KEY}" "QuietUninstallString" '"$INSTDIR\\Uninstall.exe" /S'`,
		`  WriteRegDWORD ${root} "\${UNINST_KEY}" "NoModify" 1`,
		`  WriteRegDWORD ${root} "\${UNINST_KEY}" "NoRepair" 1`,
		`  WriteRegDWORD ${root} "\${UNINST_KEY}" "EstimatedSize" ${Math.max(0, Math.round(opts.estimatedSizeKb || 0))}`,
		'SectionEnd',
		'',
		'Function .onInstSuccess',
		'  IfSilent done',
		'  MessageBox MB_YESNO|MB_ICONQUESTION "Start ${PRODUCT} now?" IDNO done',
		'  Exec \'"$INSTDIR\\${EXE}"\'',
		'  done:',
		'FunctionEnd',
		'',
		'Section "Uninstall"',
		'  !insertmacro StopApp',
		'  Delete "$SMPROGRAMS\\${PRODUCT}.lnk"',
		'  Delete "$DESKTOP\\${PRODUCT}.lnk"',
		'  RMDir /r "$INSTDIR\\resources"',
		'  RMDir /r "$INSTDIR\\locales"',
		'  Delete "$INSTDIR\\*.*"',
		'  RMDir "$INSTDIR"',
		// Shortcuts the launcher made for projects stay: they belong to the user
		`  DeleteRegKey ${root} "${q(verbKey)}"`,
		`  DeleteRegValue ${root} "${classes}${ext}\\OpenWithProgids" "${q(opts.progId)}"`,
		`  ReadRegStr $0 ${root} "${classes}${ext}" ""`,
		`  StrCmp $0 "${q(opts.progId)}" 0 +2`,
		`  DeleteRegValue ${root} "${classes}${ext}" ""`,
		`  DeleteRegKey /ifempty ${root} "${classes}${ext}\\OpenWithProgids"`,
		`  DeleteRegKey /ifempty ${root} "${classes}${ext}"`,
		`  DeleteRegKey ${root} "${classes}${q(opts.progId)}"`,
		'  System::Call \'shell32::SHChangeNotify(i 0x08000000, i 0, p 0, p 0)\'',
		`  DeleteRegKey ${root} "\${UNINST_KEY}"`,
		'SectionEnd',
		'');

	return lines.join('\n');
}
